# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
welcome: circleci/welcome-orb@0.4.1
jobs:
  build_and_save:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: /coverage
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  main:
    jobs:
      - build_and_save

      # ./node_modules/.bin